export enum Weather {
  FETCH_WEATHER_DATA_START = 'FETCH_WEATHER_DATA_START',
  FETCH_WEATHER_DATA_OK = 'FETCH_WEATHER_DATA_OK',
  FETCH_WEATHER_DATA_ERROR = 'FETCH_WEATHER_DATA_ERROR',

  FETCH_LOCAL_WEATHER_DATA_START = 'FETCH_LOCAL_WEATHER_DATA_START',
  FETCH_LOCAL_WEATHER_DATA_OK = 'FETCH_LOCAL_WEATHER_DATA_OK',
  FETCH_LOCAL_WEATHER_DATA_ERROR = 'FETCH_LOCAL_WEATHER_DATA_ERROR'
};

export enum Crypto {
  FETCH_CRYPTO_DATA_START = 'FETCH_CRYPTO_DATA_START',
  FETCH_CRYPTO_DATA_OK = 'FETCH_CRYPTO_DATA_OK',
  FETCH_CRYPTO_DATA_ERROR = 'FETCH_CRYPTO_DATA_ERROR'
};